#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../mkdirp@2.1.3/node_modules/mkdirp/dist/cjs/src/bin.js" "$@"
else
  exec node  "$basedir/../../../../../mkdirp@2.1.3/node_modules/mkdirp/dist/cjs/src/bin.js" "$@"
fi
