# ──────────────────────────────────────────────────────────────
#  master-rules.yaml   │ authoritative policy for build-all.sh
#  last-modified: 2025-08-25
# ──────────────────────────────────────────────────────────────

proxies:
  us:
    - type: socks5
      name: US-RESI
      host: 103.210.12.53
      port: 5981
      user: twozpyil
      pass: y4syr3w1dcuz

    - type: vless
      name: US-RESI2
      host: premiusa1.vpnjantit.com
      port: 10002
      user: 210fc54a-7ebd-11f0-92b9-072f1c489945
      tls: true
      ws: true
      ws_path: "/vpnjantit"
      fast_open: false

groups:
  US: [US-RESI, US-RESI2]

rules:

  # === FINANCE / PAYMENTS ===
  - { type: DOMAIN-SUFFIX, value: "paypal.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "cash.app", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "venmo.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "wise.com",  group: "US" }
  - { type: DOMAIN-SUFFIX, value: "stripe.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "link.com",   group: "US" }
  - { type: DOMAIN-SUFFIX, value: "moonpay.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "coinbase.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "chime.com", group: "US" }

  # === SIM / IDENTITY / SPOOFING ===
  - { type: DOMAIN-SUFFIX, value: "textnow.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "getsly.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "burnerapp.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "slyphone.com", group: "US" }

  # === SOCIAL / AUTH / FINGERPRINTED ===
  - { type: DOMAIN-SUFFIX, value: "snapchat.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "openai.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "claude.ai", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "anthropic.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "facebook.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "instagram.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "telegram.org", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "tiktok.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "x.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "twitter.com", group: "US" }

  # === CRYPTO ===
  - { type: DOMAIN-SUFFIX, value: "trustwallet.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "metamask.io", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "phantom.app", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "binance.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "gemini.com", group: "US" }

mitm_hostnames:
  - "*.paypal.com"
  - "*.cash.app"
  - "*.snapchat.com"
  - "*.openai.com"
  - "*.binance.com"
  - "*.wise.com"
  - "*.tiktok.com"
  - "*.instagram.com"
  - "*.claude.ai"
  - "*.api.anthropic.com"
  - "*.telegram.org"
  - "*.gemini.com"
  - "*.trustwallet.com"
  - "*.metamask.io"
  - "*.phantom.app"
  - "*.stripe.com"
  - "*.moonpay.com"
  - "*.textnow.com"
  - "*.coinbase.com"
  - "*.chime.com"

scripts:
  loader_url: "https://popdeuxrem.github.io/shadow-scripts/scripts/mitm-loader.js"

block_domains:
  - google-analytics.com
  - doubleclick.net
  - appsflyer.com
  - adjust.com
  - facebook.net
  - logrocket.io
  - metrics.stripe.com
  - r.stripe.com
  - m.stripe.com

external_rule_sets:
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/refs/heads/master/domains/openai.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/refs/heads/master/domains/discord.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/refs/heads/master/domains/facebook.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/refs/heads/master/domains/github.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/refs/heads/master/domains/instagram.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/refs/heads/master/domains/jetbrains.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/refs/heads/master/domains/linkedin.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/refs/heads/master/domains/medium.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/refs/heads/master/domains/pornhub.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/refs/heads/master/domains/reddit.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/refs/heads/master/domains/telegram.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/refs/heads/master/domains/twitter.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/refs/heads/master/domains/whatsapp.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/refs/heads/master/domains/xvideos.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/refs/heads/master/domains/youtube.list"
    group: "US"
