proxies:
  us:
    - { type: "socks5", name: "SOCKS5-US1", host: "1.2.3.4", port: 1080, user: "username", pass: "password" }
    - { type: "http", name: "HTTP-US1", host: "1.2.3.4", port: 8080, user: "username", pass: "password" }
    - { type: "vless", name: "VLESS-US1", host: "vless.example.com", port: 443, ws: true, tls: true, servername: "yourdomain.com" }
groups:
  US: [SOCKS5-US1, HTTP-US1, VLESS-US1]
rules:
  - { type: "DOMAIN-SUFFIX", value: "paypal.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "cash.app", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "venmo.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "wise.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "stripe.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "link.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "moonpay.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "textnow.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "burnerapp.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "getsly.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "slyphone.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "facebook.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "instagram.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "twitter.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "x.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "snapchat.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "discord.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "telegram.org", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "t.me", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "tiktok.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "youtube.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "netflix.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "disneyplus.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "primevideo.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "spotify.com", group: "US" }
  - { type: "DOMAIN-KEYWORD", value: "stun", group: "US" }
  - { type: "DOMAIN-KEYWORD", value: "turn", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "webrtc.org", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "manus.ai", group: "US" }
  - { type: "DOMAIN", value: "api.manus.ai", group: "US" }
  - { type: "DOMAIN", value: "ws.manus.ai", group: "US" }
  - { type: "DOMAIN", value: "cdn.manus.ai", group: "US" }
  - { type: "DOMAIN", value: "assets.manus.ai", group: "US" }
  - { type: "DOMAIN", value: "static.manus.ai", group: "US" }
  - { type: "DOMAIN", value: "www.manus.ai", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "talkroom.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "talkroom.co", group: "US" }
  - { type: "DOMAIN", value: "api.talkroom.com", group: "US" }
  - { type: "DOMAIN", value: "websocket.talkroom.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "cdn.talkroom.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "assets.talkroom.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "hostinger.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "payments.hostinger.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "api.hostinger.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "static.hostinger.com", group: "US" }
  - { type: "DOMAIN", value: "apple-pay-gateway.apple.com", group: "US" }
  - { type: "DOMAIN", value: "apple-pay-gateway-nc.apple.com", group: "US" }
  - { type: "DOMAIN", value: "apple-pay-gateway-pr.apple.com", group: "US" }
  - { type: "DOMAIN", value: "apple-pay-gateway-cert.apple.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "apple.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "pay.google.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "payments.google.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "googleapis.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "gstatic.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "js.stripe.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "stripe.network", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "checkout.stripe.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "braintreegateway.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "adyen.com", group: "US" }
  - { type: "DOMAIN-SUFFIX", value: "adyenpayments.com", group: "US" }
  # ... (you can add all other domains from your full config dump here)
mitm_hostnames:
  - "*.paypal.com"
  - "*.snapchat.com"
  - "*.openai.com"
  - "*.binance.com"
  - "*.wise.com"
  - "*.tiktok.com"
  - "*.instagram.com"
  - "*.claude.ai"
  - "*.api.anthropic.com"
  - "*.telegram.org"
  - "*.gemini.com"
  - "*.trustwallet.com"
  - "*.metamask.io"
  - "*.phantom.app"
  - "*.stripe.com"
  - "*.moonpay.com"
  - "*.textnow.com"
scripts:
  loader_url: "https://popdeuxrem.github.io/shadow-scripts/scripts/mitm-loader.js"
block_domains:
  - "google-analytics.com"
  - "doubleclick.net"
  - "appsflyer.com"
  - "adjust.com"
  - "facebook.net"
  - "logrocket.io"
external_rule_sets:
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/openai.list"
    group: "US"
  # ...add more if needed
