# ──────────────────────────────────────────────────────────────
#  master-rules.yaml   │ authoritative policy for build-all.sh
#  last-modified: 2025-08-23
# ──────────────────────────────────────────────────────────────

proxies:
  us:
    # ⚡ Residential SOCKS5
    - type: socks5
      name: US-RESI
      host: 103.210.12.53
      port: 5981
      user: twozpyil
      pass: y4syr3w1dcuz

    # ⚡ VLESS over WS+TLS (Jantit)
    - type: vless
      name: US-RESI2
      host: premiusa1.vpnjantit.com
      port: 10002
      user: 210fc54a-7ebd-11f0-92b9-072f1c489945
      tls: true
      ws: true
      ws_path: "/vpnjantit"
      fast_open: false

groups:
  # Any rule that points to group “US” will round-robin / fail-over
  US: [US-RESI, US-RESI2]

# ──────────────────────────────────────────────────────────────
#  Rules  (trimmed for brevity – identical to your last dump)
#  ↓↓↓ KEEP EVERYTHING BELOW UNCHANGED UNLESS YOU REALLY NEED TO
# ──────────────────────────────────────────────────────────────
rules:

  # === FINANCE / PAYMENTS ===
  - { type: DOMAIN-SUFFIX, value: "paypal.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "cash.app", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "venmo.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "wise.com",  group: "US" }
  - { type: DOMAIN-SUFFIX, value: "stripe.com", group: "US" }
  - { type: DOMAIN-SUFFIX, value: "link.com",   group: "US" }
  - { type: DOMAIN-SUFFIX, value: "moonpay.com",group: "US" }

  # === eSIM / BURNER ===
  - { type: DOMAIN-SUFFIX, value: "textnow.com",  group: "US" }
  - { type: DOMAIN-SUFFIX, value: "burnerapp.com",group: "US" }
  - { type: DOMAIN-SUFFIX, value: "getsly.com",   group: "US" }
  - { type: DOMAIN-SUFFIX, value: "slyphone.com", group: "US" }

  # ……………………………………………………………………………
  #  (all other rule blocks exactly as before)
  # ……………………………………………………………………………

mitm_hostnames:
  - "*.paypal.com"
  - "*.snapchat.com"
  - "*.openai.com"
  - "*.binance.com"
  - "*.wise.com"
  - "*.tiktok.com"
  - "*.instagram.com"
  - "*.claude.ai"
  - "*.api.anthropic.com"
  - "*.telegram.org"
  - "*.gemini.com"
  - "*.trustwallet.com"
  - "*.metamask.io"
  - "*.phantom.app"
  - "*.stripe.com"
  - "*.moonpay.com"
  - "*.textnow.com"

scripts:
  loader_url: "https://popdeuxrem.github.io/shadow-scripts/scripts/mitm-loader.js"

block_domains:
  - google-analytics.com
  - doubleclick.net
  - appsflyer.com
  - adjust.com
  - facebook.net
  - logrocket.io
  - metrics.stripe.com
  - r.stripe.com
  - m.stripe.com

external_rule_sets:
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/openai.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/discord.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/facebook.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/github.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/instagram.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/jetbrains.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/linkedin.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/medium.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/pornhub.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/reddit.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/redis.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/telegram.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/twitter.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/whatsapp.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/xvideos.list"
    group: "US"
  - url: "https://raw.githubusercontent.com/dlisin/shadowrocket-config/master/domains/youtube.list"
    group: "US"
